### ISSUE TITLE
请问能加入hina的光环吗？

### ISSUE THREAD

**Issue by kJNCwBUq** [MagicalAstrogy/AngelHalos#1]
如题
![](https://github.com/user-attachments/assets/a481cf20-7604-485d-8c42-685e31afe28f)

**Comment by MagicalAstrogy** [comment]
收到，在下次更新时会努力加上。

不过hina的光环结构比较复杂，在dol的分辨率下效果不一定会好。

**Comment by MagicalAstrogy** [comment]
已在 v1.6.4 增加。
